### ISSUE TITLE
kde filemanager view-modes icons too white for light themes

### ISSUE THREAD

**Issue by demoy** [alecive/FlatWoken#112]
Thanks for this awesome icon set. Image: 
![screenshot_20170114_170644](https://cloud.githubusercontent.com/assets/2396524/21958425/f19da74e-da7b-11e6-978b-7327e2484fb8.png)

Unlike other toolbar icons [up-above] view-mode icons lack a blue backdrop, making viewing difficult: 
![screenshot_20170114_171122](https://cloud.githubusercontent.com/assets/2396524/21958445/83a30fc6-da7c-11e6-8d2a-6f5a93fa09be.png)

Alternatelyly a quick compromise is to provide alternative colored icon (or tell me which directory to go to help myself)

**Comment by alecive** [comment]
I can do better :sunglasses: 
There exist a customization script in the `Extra` folder ( https://github.com/alecive/FlatWoken/blob/master/Extra/configure.sh ) that let's you change the color of the panel icons to any hex color you want. Actually, you can also change the color of the folder icons!

I never made it public because I never found time to make it robust enough, but it works and I am using it quite often :+1:

Rembember to launch the script from the folder in which it is stored, otherwise there may be some issues.

I am closing the issue for now, feel free to reopen it if it does not work! But please tell me how did it go because you would be the first user of that script :smile:

**Comment by alecive** [comment]
Btw: theoretically, the icons in the toolbar should be all monochromatic, but I think that dolphin is messing around with the icons it uses (otherwise there wouldn't be this inconsistency).

**Comment by demoy** [comment]
Cool
![screenshot_20170115_151826](https://cloud.githubusercontent.com/assets/2396524/21965830/e197664a-db35-11e6-9043-63038b46d5d8.png)
 that was easy. Love that that script has an restore option.

**Comment by alecive** [comment]
Glad it helped! :+1:
It was impossible to me to suit every need with only one color, your use case is exactly why I started tinkering with the script :smile:
